### ISSUE TITLE
Problem with 8-bit snail

### ISSUE THREAD

**Issue by desaster** [MiSTer-devel/Vector-06C_MiSTer#2] opened 2019-11-24 21:40 UTC
Hi!

I'd like to report an issue with the 8-bit snail demo on the Vector-06C core. The demo can be found (and played) here: http://sensi.org/scalar/ware/767/

There seems to be a visual problem in two parts of the demo.
* The vertically scrolling text is clipped off and misaligned
* The checkerboard background appears misaligned/clipped

The demo works properly with the [vector06js](https://github.com/svofski/vector06js) and [vector06sdl](https://github.com/svofski/vector06sdl) emulators, as well as the [vector06cc](https://github.com/svofski/vector06cc) FPGA implementation and original hardware (I've only successfully tested emulators myself). 

Below are a couple screenshots for comparison.

![snailcompare](https://user-images.githubusercontent.com/631441/69501675-ed658180-0f0f-11ea-82a7-0cc62ae9b3ec.png)

(ping @svofski)

**Comment by svofski** [comment] 2020-02-02 22:02
I can confirm that vector06js rendering is correct.

It seems that the interrupt timing in this core is off. 

For compatibility tests I can recommend checking out the tests that I use in vector06sdl:
  * https://github.com/svofski/vector06sdl/tree/master/testroms

Verified against the real hardware results are in:
  * https://github.com/svofski/vector06sdl/tree/master/test/expected

**Comment by sorgelig** [comment] 2020-02-03 18:05
So much time passed since i've worked on this core.. Hard to recall all specifics now.
Patches Fixes are welcome.

**Comment by desaster** [comment] 2020-02-09 10:51
No patches from me yet, but I've  collected some test results. Left side is Vector06C-MiSTer, right side is real hardware results from svofski's github.

## bord2.rom

<img src="https://user-images.githubusercontent.com/631441/74100486-4ff61300-4b38-11ea-8606-3fa56a9e8927.png" width="320"> <img src="https://user-images.githubusercontent.com/631441/74100492-60a68900-4b38-11ea-9819-0fe96e789c99.png" width="320">

## brdtestx.rom

<img src="https://user-images.githubusercontent.com/631441/74100562-238ec680-4b39-11ea-922a-2f3acf0f57fe.png" width="320"> <img src="https://user-images.githubusercontent.com/631441/74100564-25f12080-4b39-11ea-917d-73dea47a6206.png" width="320">

## chkvi53.rom

<img src="https://user-images.githubusercontent.com/631441/74100574-4ae59380-4b39-11ea-9804-631cb944c44c.png" width="320"> <img src="https://user-images.githubusercontent.com/631441/74100575-4d47ed80-4b39-11ea-8056-e1eb93eba881.png" width="320">

## clrs.rom

<img src="https://user-images.githubusercontent.com/631441/74100584-6d77ac80-4b39-11ea-96a6-ed52b1f123cd.png" width="320"> <img src="https://user-images.githubusercontent.com/631441/74100589-79fc0500-4b39-11ea-9d97-001d7a688af9.png" width="320">

## testtp.rom

<img src="https://user-images.githubusercontent.com/631441/74100606-b6c7fc00-4b39-11ea-9940-502917b7ab5f.png" width="320"> <img src="https://user-images.githubusercontent.com/631441/74100604-afa0ee00-4b39-11ea-98ae-aa4930821493.png" width="320">

## tst8253.rom

<img src="https://user-images.githubusercontent.com/631441/74100622-de1ec900-4b39-11ea-87ee-bc3774729c8b.png" width="320"> <img src="https://user-images.githubusercontent.com/631441/74100624-e119b980-4b39-11ea-97cc-394c764cdf6f.png" width="320">

## vst.rom

<img src="https://user-images.githubusercontent.com/631441/74100644-0ad2e080-4b3a-11ea-9f35-b9dad701ad02.png" width="320"> <img src="https://user-images.githubusercontent.com/631441/74100649-145c4880-4b3a-11ea-9578-2fe6bb4bd46e.png" width="320">

**Comment by svofski** [comment] 2020-02-10 08:05
Just to clarify, my screens above are not directly pulled from the real hardware, but visually matched against it. May seem like pedantry, but there is a possibility of some single pixel offsets in the raster tests.

There is also a visual artifact that emulators tend to ignore: a bright pixel at the exact moment of palette writes. This can be seen as thin vertical stripes in clrs.rom (256 colour test). I personally think it should not be emulated.

**Comment by svofski** [comment] 2020-02-10 11:49
Just in case it might come in handy, this is the development log of sorts:

https://zx-pk.ru/threads/26199-voprosy-po-vektoru-(dlya-emulyatora).html

**Comment by sorgelig** [comment] 2020-02-10 16:41
Funny to see the link to my topic ;)

**Comment by sorgelig** [comment] 2020-06-05 17:44
Ok, that was my mistake in some earlier commit when it got broken. I remember demos and these tests were correct.
Anyway it's fixed in today's release.

**Comment by desaster** [comment] 2020-06-05 18:10
Nice, thank you! I just tested 8-bit snail and can confirm that the issue is fixed.

There maybe some problem with audio, but I can open another issue for it once I have the time to test further.

**Comment by desaster** [comment] 2020-06-05 18:23
disregard the comment about audio, with 100% stereo mix it's fine

**Comment by sorgelig** [comment] 2020-06-05 18:47
good. then i close it.

**Closed as completed by sorgelig** 2020-06-05 18:47 UTC
